### ISSUE TITLE
PULLREQ_EDITMSG sometimes shows incorrect head

### ISSUE THREAD

**Issue by terminalmage** [mislav/hub#1360]
```
% hub --version
git version 2.10.2
hub version 2.2.9
```

Sometimes the PULLREQ_EDITMSG shows an incorrect head branch in the top comment line. I'm not sure if this is because the PULLREQ_EDITMSG was created incorrectly, or if the PULLREQ_EDITMSG isn't being cleaned after a previous PR is opened and it is just being re-used, but occasionally I see a different head branch from the one I specified (or a different one from the currently-checked-out branch if I'm not specifying a head branch). However, I can still proceed to open the PR, and it gets opened with the correct head branch. So this is more of a cosmetic issue that causes confusion, and not a matter of hub incorrectly opening the PR.

I'm sorry that I don't have more detailed information on how to reproduce, but I haven't yet noticed a pattern to what causes this. I'm hoping the fact that there are likely only a few places where PULLREQ_EDITMSG is handled, and the fact that hub still opens the PR using the correct head branch, are together enough to help narrow it down.

**Comment by terminalmage** [comment]
Another side-effect of this is that the pull request title that is pre-filled in the PULLREQ_EDITMSG is the one from the incorrect head branch. This actually happened in [this PR](https://github.com/saltstack/salt/pull/38191) and I didn't notice it until now.

**Comment by mislav** [comment]
Thanks for reporting. Hub tries to re-use the old `PULLREQ_EDITMSG` file when such file exists, and this is the most likely cause for the stale head to be displayed (or stale title, for that matter). The `PULLREQ_EDITMSG` file, however, should always be deleted after a successful pull request. Hub only keeps it if the response from the server was something unexpected, so you don't lose everything that you've written in the file.

Have any pull requests failed for you prior to opening new ones? Do you see `.git/PULLREQ_EDITMSG` kept even after a successful PR opened?

**Comment by terminalmage** [comment]
I did notice a couple of ``PULLREQ_EDITMSG`` files, both in ``.git/`` and in the worktree dirs under ``.git/worktrees/``. I think however, that at least _some_ of these exist because I was seeing bad info in the ``PULLREQ_EDITMSG`` and was pre-emptively killing the tmux pane in which my editor was open to avoid opening a PR with the bad info in it. I've removed all of these ``PULLREQ_EDITMSG`` files and will continue to observe whether or not this problem re-occurs.

One potential explanation could be that hub was looking for ``.git/PULLREQ_EDITMSG`` when in a git worktree (i.e. ``git worktree add ......``), rather than in the worktree dir. Before I opened this issue I noticed that there was a stale ``.git/PULLREQ_EDITMSG``, though I was too dumb to look at the contents before I deleted it. I almost exclusively work in git worktrees, so it is not out of the question for there to have been a stale ``PULLREQ_EDITMSG`` there for months without me noticing. I have a feeling that the cause of me forcibly killing vim to avoid opening a PR using a bad ``PULLREQ_EDITMSG`` may have been the fact that hub was still looking in ``.git/`` instead of ``.git/worktrees/worktree_name``. However, I just tried to reproduce this by creating a dummy ``.git/PULLREQ_EDITMSG`` and then attempted to open a PR from a worktree and hub correctly created a new ``PULLREQ_EDITMSG`` in the worktree dir and ignored ``.git/PULLREQ_EDITMSG``. So, the stale ``PULLREQ_EDITMSG`` files in some of my old worktrees (which I should really clean out sometime :smile:) may date from a time when there was a bug in an older release of hub. https://github.com/github/hub/issues/877 and https://github.com/github/hub/issues/928 are a couple that dealt with similar issues.

The issue that caused me to open this bug report occurred in one of the rare times where I opened a PR from the "main" git clone (i.e. not from a worktree), so the explanation of hub re-using an existing ``PULLREQ_EDITMSG`` holds, since I _did_ find one there. However, side note, it might be a good idea for hub to treat ``PULLREQ_EDITMSG`` files older than N days as stale and disregard them. If this age were tunable, that'd be even better!

Like I said, I'll continue to keep an eye out. This may indeed be a relic of an older, since-fixed issue, so you can feel free to close this if you like and we can re-open if I find specific circumstances where a ``PULLREQ_EDITMSG`` is left behind after a PR is successfully opened.

**Comment by mislav** [comment]
You might be on to something re: worktrees. I have no idea how this feature plays together with switching between worktrees, because I'm not a heavy user of those. 🤔

**Comment by terminalmage** [comment]
Yeah, but I couldn't even reproduce it in hub 2.2.9, so it's probably not worth chasing that thread right now.

It would definitely be nice to be able to disregard ``PULLREQ_EDITMSG`` files older than a given age, though.

**Comment by terminalmage** [comment]
Oh, one other thing I noticed, is that when a ``PULLREQ_EDITMSG`` is reused, even if you don't save the file, hub seems to continue with opening the PR. Normally, if you exit your editor without saving the file, hub will abort and not try to open a PR, but it seems like it is only doing a check for the existence of that file and deciding that if it exists, that a PR should be opened.

To fix this, when a ``PULLREQ_EDITMSG`` is being re-used, hub could ``os.Stat()`` the file before and after, and only open the PR if the modified time has changed. That would keep it from opening a PR if someone exits their editor without saving the file.

Should I open separate issues for this and the above request?

**Comment by mislav** [comment]
> even if you don't save the file, hub seems to continue with opening the PR. Normally, if you exit your editor without saving the file, hub will abort and not try to open a PR

You noticed this correctly, but what if a person wants to post the original text that they wrote without any modifications? Maybe the first time around it failed because of a network error.

**Comment by terminalmage** [comment]
My solution of performing an ``os.Stat()`` on the file before and after (in cases where a ``PULLREQ_EDITMSG`` is being re-used) would catch this. It would allow one to exit the editor without saving, and abort opening the PR.

If one wishes to re-attempt the previously-failed PR but not change the contents of the ``PULLREQ_EDITMSG``, they can simply save before exiting, which will change the mtime of the file. If the mtime from the ``os.Stat()`` taken after one exits the editor differs from that of the file before the editor was launched, then we know that the file was saved. Coaching users on observing this new behavior would be easy to do, a simple message can be printed to the screen saying something like "Aborted opening pull request due to unmodified buffer. If you wish to submit the pull request, save the buffer before exiting."

This, to me, would make opening a PR that previously failed act more like opening a PR for the first time, in that one would have the option of aborting by not saving the ``PULLREQ_EDITMSG`` before closing their editor. Right now, if the PR fails the first time, there is no way to back out if you run another ``hub pull-request`` and an existing ``PULLREQ_EDITMSG`` is used. That kinda sucks.

**Comment by mislav** [comment]
> If one wishes to re-attempt the previously-failed PR but not change the contents of the `PULLREQ_EDITMSG`, they can simply save before exiting, which will change the mtime of the file.

That's a good idea. Want to try to code it up?

> if the PR fails the first time, there is no way to back out if you run another `hub pull-request` and an existing `PULLREQ_EDITMSG` is used.

Well, if you have an editor that can exit with a nonzero status, such as `:cq` in vim, you can abort opening the PR. But people with graphical text editors likely don't have access to such a feature.

**Comment by terminalmage** [comment]
@mislav sure, I can give it a try. My go-fu is nowhere near as good as my Python-fu though, so anything I submit should be double and triple-scrutinized. I'll try to hack away at it this weekend.

**Comment by mislav** [comment]
Feel free to submit a mess and I can clean it up. [Here is where I think the logic could go](https://github.com/github/hub/blob/b1c1cbd0492a31e95035c615c224f3c0c44bf351/github/editor.go#L74-L86); there should be a check that mtime got updated after `openEditor()` call, otherwise assume that the person didn't save the file.

Some tests might get broken with the new logic, because they simulate a fake editor being opened, but not all of them bump the mtime. If you get lost in there, I can help out.

**Comment by terminalmage** [comment]
Cool, thanks!

**Comment by strk** [comment]
I'm having the same problem, template having the wrong .Base, no matter what I pass with `-b`.

**Comment by terminalmage** [comment]
@mislav I did not get around to this over the weekend, and it doesn't look like I'd even have a chance to start until after the holidays. So if you have the time and want to hack at it, go for it.
