### ISSUE TITLE
hub asking for username and password when used with ssh protocol

### ISSUE THREAD

**Issue by metapraveen** [mislav/hub#3011]
**Command attempted:**
hub clone dot-files

**What happened:**
promts for username

**More info:**
git config --global hub.protocol
ssh

hub --version
git version 2.37.0 (Apple Git-136)
hub version refs/heads/master

OS
macOS 12.6 (21G115)

Giving full URL works fine for e.g. ```hub clone git@github.com:metapraveen/dot-files.git``` clones the repo via ssh auth

**Comment by chaimleib** [comment]
`hub` is failing for me like this, too, anytime I try something that requires authentication. `git clone` and `git push` work, but not the `hub` versions of these commands.

```
(master) % hub create
github.com username: chaimleib
github.com password for chaimleib (never stored):
Error creating repository: Not Found (HTTP 404)
Not Found
```

```
% hub --version
git version 2.38.2
hub version 2.14.2
```

I've tried both of these:
```
% git config --global hub.protocol https
% git config --global hub.protocol ssh
```

I have URL replacement on to force ssh instead of https on github, but both above configs also fail, even if I turn replacement off:
```
[url "git@github.com:"]
	insteadOf = https://github.com/
```

macOS 10.15.7

**Comment by fatso83** [comment]
Yeah, hub has not been usable for anything for the last six months. Only auth errors and no prompting to authenticate using browser or similar.

**Comment by daiyam** [comment]
OK It's not just me. Same issue.

**Comment by fatso83** [comment]
That is a workaround, not a fix. A better workaround is to just ditch Hub for the official GitHub CLI, as Hub is essentially deprecated: https://mislav.net/2020/01/github-cli. All of Mislav's efforts go into that these days and I have been able to transition from all current Hub commands to `gh` very easily (i.e.  `gh pr checkout <issue>`, `gh browse`, ...)
